fix deploy

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -58,20 +58,37 @@ jobs:
           context: ./nginx
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_gateway:latest
           push: true
-
   deploy:
     needs: build-and-push
     runs-on: ubuntu-latest
     steps:
-      - name: Ensure target directory exists
+      - name: Install Docker
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.SSH_HOST }}
           username: ${{ secrets.SSH_USERNAME }}
           key: ${{ secrets.SSH_KEY }}
           script: |
-            mkdir -p ~/kittygram
-            echo "Target directory created or already exists."
+            # Установка Docker
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker not found, installing..."
+              sudo apt update
+              sudo apt install -y docker.io
+              sudo systemctl start docker
+              sudo systemctl enable docker
+            else
+              echo "Docker is already installed."
+            fi
+
+            # Добавление пользователя в группу Docker
+            if ! groups | grep -q "\bdocker\b"; then
+              echo "Adding user to docker group..."
+              sudo usermod -aG docker $USER
+            fi
+
+            # Проверка установки Docker
+            docker --version
 
       - name: Deploy to server
         uses: appleboy/ssh-action@master
